"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeft,
  Key,
  Settings,
  Users,
  Activity,
  Copy,
  Eye,
  EyeOff,
  Plus,
  Trash2,
  CheckCircle,
  Mail,
  Github,
  Shield,
} from "lucide-react";

interface Project {
  id: string;
  name: string;
  slug: string;
  isActive: boolean;
  createdAt: string;
  allowedOrigins: string[];
}

interface AuthSettings {
  projectId: string;
  enableEmailPassword: boolean;
  enableGoogleOAuth: boolean;
  enableGithubOAuth: boolean;
  requireEmailVerification: boolean;
  allowSignup: boolean;
}

interface ApiKey {
  id: string;
  type: "publishable" | "secret";
  keyPrefix: string;
  name: string | null;
  revoked: boolean;
  createdAt: string;
  lastUsedAt: string | null;
}

export default function ProjectDetailPage() {
  const params = useParams();
  const router = useRouter();
  const projectId = params?.projectId as string;

  const [project, setProject] = useState<Project | null>(null);
  const [authSettings, setAuthSettings] = useState<AuthSettings | null>(null);
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showNewKeyModal, setShowNewKeyModal] = useState(false);
  const [newKeyType, setNewKeyType] = useState<"publishable" | "secret">(
    "publishable",
  );
  const [newKeyName, setNewKeyName] = useState("");
  const [generatedKey, setGeneratedKey] = useState("");
  const [visibleKeys, setVisibleKeys] = useState<Record<string, string>>({});
  const [copiedKey, setCopiedKey] = useState("");
  const [savingAuthSettings, setSavingAuthSettings] = useState(false);

  useEffect(() => {
    if (projectId) {
      fetchProject();
      fetchKeys();
    }
  }, [projectId]);

  const fetchProject = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}`);
      if (!res.ok) throw new Error("Failed to fetch project");
      const data = await res.json();
      setProject(data.project);
      setAuthSettings(data.authSettings);
    } catch (err) {
      setError("Failed to load project");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const fetchKeys = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}/keys`);
      if (!res.ok) throw new Error("Failed to fetch keys");
      const data = await res.json();
      setKeys(data.keys || []);

      // Auto-generate dev keys if none exist
      if (!data.keys || data.keys.length === 0) {
        await autoGenerateDevKeys();
      }
    } catch (err) {
      console.error("Failed to load keys:", err);
    }
  };

  const autoGenerateDevKeys = async () => {
    try {
      // Generate publishable dev key
      await fetch(`/api/projects/${projectId}/keys`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "publishable",
          name: "Development Publishable Key",
          environment: "dev",
        }),
      });

      // Generate secret dev key
      await fetch(`/api/projects/${projectId}/keys`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "secret",
          name: "Development Secret Key",
          environment: "dev",
        }),
      });

      // Refresh keys list
      const res = await fetch(`/api/projects/${projectId}/keys`);
      const data = await res.json();
      setKeys(data.keys || []);
    } catch (err) {
      console.error("Failed to auto-generate keys:", err);
    }
  };

  const updateAuthSettings = async (updates: Partial<AuthSettings>) => {
    if (!authSettings) return;

    setSavingAuthSettings(true);
    try {
      const res = await fetch(`/api/projects/${projectId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          authConfig: { ...authSettings, ...updates },
        }),
      });

      if (!res.ok) throw new Error("Failed to update settings");

      const data = await res.json();
      setAuthSettings(data.authSettings);
    } catch (err) {
      console.error("Failed to update auth settings:", err);
      setError("Failed to save settings");
    } finally {
      setSavingAuthSettings(false);
    }
  };

  const handleCreateKey = async () => {
    try {
      const res = await fetch(`/api/projects/${projectId}/keys`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: newKeyType,
          name: newKeyName || undefined,
          environment: "dev",
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to create key");
      }

      const data = await res.json();
      setGeneratedKey(data.key); // The actual key value, only shown once

      // Store the visible full key temporarily
      visibleKeys[data.keyInfo.id] = data.key;

      setKeys([...keys, data.keyInfo]);
      setNewKeyName("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create key");
    }
  };

  const toggleKeyVisibility = async (keyId: string, keyPrefix: string) => {
    if (visibleKeys[keyId]) {
      // Hide the key
      const newVisible = { ...visibleKeys };
      delete newVisible[keyId];
      setVisibleKeys(newVisible);
    } else {
      // Show masked version (we don't have the full key anymore)
      alert(
        "Full key can only be viewed once during creation. This is a security feature.",
      );
    }
  };

  const copyToClipboard = (text: string, keyId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(keyId);
    setTimeout(() => setCopiedKey(""), 2000);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-500"></div>
      </div>
    );
  }

  if (!project) {
    return (
      <div className="text-center py-12">
        <p className="text-gray-400">Project not found</p>
        <Link
          href="/dashboard/projects"
          className="text-indigo-400 hover:text-indigo-300 mt-4 inline-block"
        >
          Back to Projects
        </Link>
      </div>
    );
  }

  return (
    <div>
      <Link
        href="/dashboard/projects"
        className="inline-flex items-center gap-2 text-gray-400 hover:text-gray-200 mb-6 transition"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Projects
      </Link>

      {/* Project Header */}
      <div className="bg-gray-900 border border-gray-800 rounded-lg p-6 mb-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-white">{project.name}</h1>
            <p className="text-gray-400 mt-1">/{project.slug}</p>
          </div>
          <span
            className={`px-3 py-1 rounded-full text-sm font-medium ${
              project.isActive
                ? "bg-green-500/10 text-green-400"
                : "bg-gray-800 text-gray-400"
            }`}
          >
            {project.isActive ? "Active" : "Inactive"}
          </span>
        </div>
      </div>

      {/* Authentication Configuration */}
      {authSettings && (
        <div className="bg-gray-900 border border-gray-800 rounded-lg p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <Shield className="w-5 h-5 text-indigo-400" />
            <h2 className="text-xl font-semibold text-white">
              Authentication Methods
            </h2>
          </div>
          <p className="text-gray-400 text-sm mb-6">
            Configure how users can sign in to your application
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Email/Password */}
            <div
              className={`p-4 border rounded-lg transition cursor-pointer ${
                authSettings.enableEmailPassword
                  ? "bg-indigo-500/10 border-indigo-500/50"
                  : "bg-gray-800 border-gray-700 hover:border-gray-600"
              }`}
              onClick={() =>
                updateAuthSettings({
                  enableEmailPassword: !authSettings.enableEmailPassword,
                })
              }
            >
              <div className="flex items-start justify-between mb-3">
                <Mail className="w-5 h-5 text-gray-400" />
                <div
                  className={`w-10 h-6 rounded-full transition relative ${
                    authSettings.enableEmailPassword
                      ? "bg-indigo-600"
                      : "bg-gray-700"
                  }`}
                >
                  <div
                    className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${
                      authSettings.enableEmailPassword
                        ? "transform translate-x-4"
                        : ""
                    }`}
                  />
                </div>
              </div>
              <h3 className="font-medium text-white mb-1">Email & Password</h3>
              <p className="text-xs text-gray-400">
                Traditional email/password sign-in
              </p>
            </div>

            {/* Google OAuth */}
            <div
              className={`p-4 border rounded-lg transition cursor-pointer ${
                authSettings.enableGoogleOAuth
                  ? "bg-indigo-500/10 border-indigo-500/50"
                  : "bg-gray-800 border-gray-700 hover:border-gray-600"
              }`}
              onClick={() =>
                updateAuthSettings({
                  enableGoogleOAuth: !authSettings.enableGoogleOAuth,
                })
              }
            >
              <div className="flex items-start justify-between mb-3">
                <svg
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <path
                    fill="#EA4335"
                    d="M5.26620003,9.76452941 C6.19878754,6.93863203 8.85444915,4.90909091 12,4.90909091 C13.6909091,4.90909091 15.2181818,5.50909091 16.4181818,6.49090909 L19.9090909,3 C17.7818182,1.14545455 15.0545455,0 12,0 C7.27006974,0 3.1977497,2.69829785 1.23999023,6.65002441 L5.26620003,9.76452941 Z"
                  />
                  <path
                    fill="#34A853"
                    d="M16.0407269,18.0125889 C14.9509167,18.7163016 13.5660892,19.0909091 12,19.0909091 C8.86648613,19.0909091 6.21911939,17.076871 5.27698177,14.2678769 L1.23746264,17.3349879 C3.19279051,21.2936293 7.26500293,24 12,24 C14.9328362,24 17.7353462,22.9573905 19.834192,20.9995801 L16.0407269,18.0125889 Z"
                  />
                  <path
                    fill="#4A90E2"
                    d="M19.834192,20.9995801 C22.0291676,18.9520994 23.4545455,15.903663 23.4545455,12 C23.4545455,11.2909091 23.3454545,10.5272727 23.1818182,9.81818182 L12,9.81818182 L12,14.4545455 L18.4363636,14.4545455 C18.1187732,16.013626 17.2662994,17.2212117 16.0407269,18.0125889 L19.834192,20.9995801 Z"
                  />
                  <path
                    fill="#FBBC05"
                    d="M5.27698177,14.2678769 C5.03832634,13.556323 4.90909091,12.7937589 4.90909091,12 C4.90909091,11.2182781 5.03443647,10.4668121 5.26620003,9.76452941 L1.23999023,6.65002441 C0.43658717,8.26043162 0,10.0753848 0,12 C0,13.9195484 0.444780743,15.7301709 1.23746264,17.3349879 L5.27698177,14.2678769 Z"
                  />
                </svg>
                <div
                  className={`w-10 h-6 rounded-full transition relative ${
                    authSettings.enableGoogleOAuth
                      ? "bg-indigo-600"
                      : "bg-gray-700"
                  }`}
                >
                  <div
                    className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${
                      authSettings.enableGoogleOAuth
                        ? "transform translate-x-4"
                        : ""
                    }`}
                  />
                </div>
              </div>
              <h3 className="font-medium text-white mb-1">Google</h3>
              <p className="text-xs text-gray-400">Sign in with Google</p>
            </div>

            {/* GitHub OAuth */}
            <div
              className={`p-4 border rounded-lg transition cursor-pointer ${
                authSettings.enableGithubOAuth
                  ? "bg-indigo-500/10 border-indigo-500/50"
                  : "bg-gray-800 border-gray-700 hover:border-gray-600"
              }`}
              onClick={() =>
                updateAuthSettings({
                  enableGithubOAuth: !authSettings.enableGithubOAuth,
                })
              }
            >
              <div className="flex items-start justify-between mb-3">
                <Github className="w-5 h-5 text-gray-400" />
                <div
                  className={`w-10 h-6 rounded-full transition relative ${
                    authSettings.enableGithubOAuth
                      ? "bg-indigo-600"
                      : "bg-gray-700"
                  }`}
                >
                  <div
                    className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${
                      authSettings.enableGithubOAuth
                        ? "transform translate-x-4"
                        : ""
                    }`}
                  />
                </div>
              </div>
              <h3 className="font-medium text-white mb-1">GitHub</h3>
              <p className="text-xs text-gray-400">Sign in with GitHub</p>
            </div>
          </div>

          {savingAuthSettings && (
            <div className="mt-4 text-sm text-indigo-400">Saving...</div>
          )}
        </div>
      )}

      {/* Development Keys Section */}
      <div className="bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/30 rounded-lg p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Key className="w-5 h-5 text-indigo-400" />
          <h2 className="text-xl font-semibold text-white">
            Development Mode Keys
          </h2>
          <span className="px-2 py-1 bg-indigo-500/20 text-indigo-300 text-xs rounded-full">
            Auto-generated
          </span>
        </div>
        <p className="text-gray-400 text-sm mb-6">
          Use these keys for development and testing. They're automatically
          generated when you create a project.
        </p>

        <div className="space-y-4">
          {keys
            .filter((key) => key.keyPrefix.includes("_dev_"))
            .map((key) => (
              <div
                key={key.id}
                className="p-4 bg-gray-900 border border-gray-700 rounded-lg"
              >
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <span
                      className={`px-2 py-1 rounded text-xs font-medium ${
                        key.type === "publishable"
                          ? "bg-blue-500/20 text-blue-300"
                          : "bg-purple-500/20 text-purple-300"
                      }`}
                    >
                      {key.type === "publishable" ? "Publishable" : "Secret"}
                    </span>
                    {key.name && (
                      <span className="text-sm text-gray-300">{key.name}</span>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <code className="flex-1 text-sm font-mono bg-gray-800 text-gray-300 px-3 py-2 rounded border border-gray-700 overflow-x-auto">
                    {visibleKeys[key.id]
                      ? visibleKeys[key.id]
                      : key.keyPrefix + "•".repeat(48)}
                  </code>
                  <button
                    onClick={() =>
                      copyToClipboard(
                        visibleKeys[key.id] || key.keyPrefix + "•".repeat(48),
                        key.id,
                      )
                    }
                    className="p-2 hover:bg-gray-800 rounded transition"
                    title="Copy to clipboard"
                  >
                    {copiedKey === key.id ? (
                      <CheckCircle className="w-4 h-4 text-green-400" />
                    ) : (
                      <Copy className="w-4 h-4 text-gray-400" />
                    )}
                  </button>
                </div>

                <div className="mt-2 text-xs text-gray-500">
                  {key.type === "publishable" ? (
                    <span>✓ Safe to use in client-side code</span>
                  ) : (
                    <span>⚠️ Keep secret - use only in backend code</span>
                  )}
                </div>
              </div>
            ))}
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div className="bg-gray-900 border border-gray-800 rounded-lg p-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-indigo-500/10 rounded-lg">
              <Key className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
              <p className="text-sm text-gray-400">API Keys</p>
              <p className="text-2xl font-bold text-white">{keys.length}</p>
            </div>
          </div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-lg p-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-blue-500/10 rounded-lg">
              <Users className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <p className="text-sm text-gray-400">Users</p>
              <p className="text-2xl font-bold text-white">0</p>
            </div>
          </div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-lg p-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-green-500/10 rounded-lg">
              <Activity className="w-6 h-6 text-green-400" />
            </div>
            <div>
              <p className="text-sm text-gray-400">Active Sessions</p>
              <p className="text-2xl font-bold text-white">0</p>
            </div>
          </div>
        </div>
      </div>

      {error && (
        <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg mb-6">
          {error}
        </div>
      )}

      {/* API Keys Section */}
      <div className="bg-gray-900 border border-gray-800 rounded-lg p-6 mb-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-semibold text-white">All API Keys</h2>
            <p className="text-gray-400 text-sm mt-1">
              Manage all your project's authentication keys
            </p>
          </div>
          <button
            onClick={() => setShowNewKeyModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-500 transition"
          >
            <Plus className="w-4 h-4" />
            New Key
          </button>
        </div>

        {keys.length === 0 ? (
          <div className="text-center py-12 border-2 border-dashed border-gray-700 rounded-lg">
            <Key className="w-12 h-12 text-gray-600 mx-auto mb-4" />
            <p className="text-gray-400 mb-4">
              Generating your development keys...
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {keys.map((key) => (
              <div
                key={key.id}
                className={`p-4 bg-gray-800 border rounded-lg ${
                  key.revoked
                    ? "border-red-500/30 opacity-60"
                    : "border-gray-700"
                }`}
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          key.type === "publishable"
                            ? "bg-blue-500/20 text-blue-300"
                            : "bg-purple-500/20 text-purple-300"
                        }`}
                      >
                        {key.type}
                      </span>
                      {key.name && (
                        <span className="text-sm font-medium text-gray-300">
                          {key.name}
                        </span>
                      )}
                      {key.revoked && (
                        <span className="px-2 py-1 bg-red-500/20 text-red-300 rounded text-xs font-medium">
                          Revoked
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <code className="text-sm font-mono bg-gray-900 text-gray-400 px-3 py-1 rounded">
                        {key.keyPrefix + "•".repeat(48)}
                      </code>
                      <button
                        onClick={() =>
                          copyToClipboard(key.keyPrefix + "...", key.id)
                        }
                        className="p-1 hover:bg-gray-700 rounded transition"
                      >
                        {copiedKey === key.id ? (
                          <CheckCircle className="w-4 h-4 text-green-400" />
                        ) : (
                          <Copy className="w-4 h-4 text-gray-400" />
                        )}
                      </button>
                    </div>
                    <p className="text-xs text-gray-500 mt-2">
                      Created {new Date(key.createdAt).toLocaleDateString()}
                      {key.lastUsedAt &&
                        ` • Last used ${new Date(key.lastUsedAt).toLocaleDateString()}`}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* New Key Modal */}
      {showNewKeyModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-900 border border-gray-800 rounded-lg max-w-md w-full p-6">
            {!generatedKey ? (
              <>
                <h3 className="text-xl font-semibold text-white mb-4">
                  Create New API Key
                </h3>
                <div className="space-y-4">
                  <div>
                    <label
                      htmlFor="keyType"
                      className="block text-sm font-medium text-gray-300 mb-2"
                    >
                      Key Type
                    </label>
                    <select
                      id="keyType"
                      value={newKeyType}
                      onChange={(e) =>
                        setNewKeyType(
                          e.target.value as "publishable" | "secret",
                        )
                      }
                      className="w-full px-4 py-2 bg-gray-800 border border-gray-700 text-white rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none"
                    >
                      <option value="publishable">
                        Publishable Key (Frontend)
                      </option>
                      <option value="secret">Secret Key (Backend)</option>
                    </select>
                    <p className="text-xs text-gray-400 mt-1">
                      {newKeyType === "publishable"
                        ? "Safe to use in client-side code"
                        : "Keep this secret! Only use server-side"}
                    </p>
                  </div>

                  <div>
                    <label
                      htmlFor="keyName"
                      className="block text-sm font-medium text-gray-300 mb-2"
                    >
                      Key Name (Optional)
                    </label>
                    <input
                      id="keyName"
                      type="text"
                      value={newKeyName}
                      onChange={(e) => setNewKeyName(e.target.value)}
                      className="w-full px-4 py-2 bg-gray-800 border border-gray-700 text-white rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none placeholder-gray-500"
                      placeholder="Production Key"
                    />
                  </div>

                  <div className="flex gap-3 mt-6">
                    <button
                      onClick={handleCreateKey}
                      className="flex-1 bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-500 transition"
                    >
                      Create Key
                    </button>
                    <button
                      onClick={() => {
                        setShowNewKeyModal(false);
                        setNewKeyName("");
                        setError("");
                      }}
                      className="px-6 py-2 border border-gray-700 text-gray-300 rounded-lg hover:bg-gray-800 transition"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              </>
            ) : (
              <>
                <h3 className="text-xl font-semibold text-white mb-4">
                  API Key Created!
                </h3>
                <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4 mb-4">
                  <p className="text-sm text-yellow-300 font-medium mb-2">
                    ⚠️ Save this key now!
                  </p>
                  <p className="text-xs text-yellow-200/80">
                    You won't be able to see the full key again. Store it
                    securely.
                  </p>
                </div>
                <div className="bg-gray-800 rounded-lg p-4 mb-4 border border-gray-700">
                  <code className="text-sm font-mono text-gray-300 break-all">
                    {generatedKey}
                  </code>
                </div>
                <button
                  onClick={() => {
                    copyToClipboard(generatedKey, "new");
                  }}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-500 transition mb-3"
                >
                  <Copy className="w-4 h-4" />
                  {copiedKey === "new" ? "Copied!" : "Copy to Clipboard"}
                </button>
                <button
                  onClick={() => {
                    setShowNewKeyModal(false);
                    setGeneratedKey("");
                    setNewKeyName("");
                    setError("");
                  }}
                  className="w-full px-4 py-2 border border-gray-700 text-gray-300 rounded-lg hover:bg-gray-800 transition"
                >
                  Done
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
